// 定義不同語言的文本內容
const translations = {
	en: {
		header: "Ray's Gamepad Tester",
		oscilloscope: "Oscilloscope",
		home: "Home",
		linearity: "Linearity",
		staticNoise: "Static Noise Test",
		wobbleTest: "Wobble Check",
		roundness: "Roundness Test",
		directionCheck: "Direction Check",
		none: "None",
		original: "The original output.",
		general: "General:",
		amp: "Output Amplify",
		deadzone: "Deadzone",
		roundLock: "Round Lock",
		individual: "Individual:",
		edge: "Edge Compensation (Draw 3 circles)",
		left: "Left Joystick:",
		right: "Right Joystick:",
		bg: "Background Color:",
		black: "BLACK",
		linearityStd: "Independent Linearity Standard:",
		require: "(Requires special tool.)",
		xpush: "X Axis Push",
		ypush: "Y Axis Push",
		xreturn: "X Axis Return",
		yreturn: "Y Axis Return",
		copyright: "© 2024 Ray Liu. All rights reserved.",
		range: "Range",
		rj: "Right Joystick",
		lj: "Left Joystick",
		inspection: "Inspection",
		slideNoise: "Slide Noise Test",
		game: "Game",
		track: "Show Track",
		static: "Static Noise",
		slide: "Slide Noise",
		return: "Return Position",
		balance: "Balance",
		item: "Settings",
		xSwap: "Swap X Axis",
		ySwap: "Swap Y Axis",
		centerDVTest: "Center DV Test",
		balanceTest: "Balance Test",
		switchTest: "Switch Test",
		tolerance: "Tolerance",
		maxDV: "Max DV",
		minDV: "Min DV",
		only4: "4 Directions Only",
		noFill: "No Fill",
		slideNoiseMax: "Slide Noise < ",
		staticNoiseMax: "Static Noise < ",
		balanceErr: "Tolerance < ",
		sample: "Take Sample",
		rotateUL: "Clockwise from the upper right.",
		sampleRing: "Use Auto Sampling Ring",
		startTest: "Start Test (Space)",
		autoRetest: "Auto Retest",
		saveData: "Save Data (Enter)",
		saveOnSwitch: "Save when testing switch",
		model: "Model",
		saved: "Data Saved",
		nowDV: "Current DV",
		leftDV: "Left Return DV",
		rightDV: "Right Return DV",
		returnAccuracy: "Return Accuracy",
		upDV: "Up Return DV",
		downDV: "Down Return DV",
		checkSaved: "Check Saved Data",
		compensation: "Compensation Simulation",
		centerDV: "Center DV",
		DVRange: "DV Range",
		direction: "Direction",
		wobble: "Wobble",
		switch: "Switch",
		useReturnCenter: "Use Return Center Calculation",
		rangeDV: "DV Range:",
		rangeMax: "Max Range",
		returnErr: "Tolerance: 50% ± ",
		onesideDV: "One-side DV ≧ ",
		singleDirectionLifeTest: "Single Direction Life Test",
		LJoystick: "Left Joystick",
		RJoystick: "Right Joystick",
		testRange: "Range",
		noiseMax: "Max Noise",
		affectAxis: "Affect Other Axis",
		cleanTrack: "Clean",
		sec: "sec",
		noise: "Noise",
		interference: "Interference",
		sw: "SW",
		up: "Up",
		down: "Down",
		left: "Left",
		right: "Right",
		clear: "Clear",
		detail: "Detail",
		xAxis: "X Axis",
		yAxis: "Y Axis",
	},
	zh: {
		header: "Ray的手柄測試工具",
		oscilloscope: "示波器",
		home: "首頁",
		linearity: "線性測試",
		staticNoise: "靜態雜波測試",
		wobbleTest: "復歸精度測試",
		roundness: "最大/最小分壓測試",
		directionCheck: "檢查旋轉方向",
		none: "無校正",
		original: "原始輸出",
		general: "通用型：",
		amp: "輸出放大百分比",
		deadzone: "死區百分比",
		roundLock: "外圓鎖定",
		individual: "單體校正：",
		edge: "尋邊校正(左右搖桿各轉三圈)",
		left: "左搖桿：",
		right: "右搖桿：",
		bg: "背景顏色：",
		black: "黑色",
		linearityStd: "獨立線性測試標準",
		require: "(需要特殊測試制具)",
		xpush: "X軸去程",
		ypush: "Y軸去程",
		xreturn: "X軸返程",
		yreturn: "Y軸返程",
		copyright: "© 2024 Ray Liu. 保留所有權利。",
		range: "範圍",
		rj: "右搖桿",
		lj: "左搖桿",
		inspection: "全檢",
		slideNoise: "滑動雜音測試",
		game: "小遊戲",
		track: "顯示軌跡",
		static: "靜態雜波",
		slide: "滑動雜音",
		return: "復歸位置",
		balance: "對稱性",
		item: "測試項目與設置",
		xSwap: "x軸(左右)對調",
		ySwap: "y軸(上下)對調",
		centerDVTest: "中心分壓測試 (必檢)",
		balanceTest: "對稱性測試",
		switchTest: "開關測試",
		tolerance: "正負公差",
		maxDV: "上分壓",
		minDV: "下分壓",
		only4: "只測四方向",
		noFill: "不上色",
		slideNoiseMax: "滑動雜音 < ",
		staticNoiseMax: "靜態雜波 < ",
		balanceErr: "公差 < ",
		sample: "進行採樣",
		rotateUL: "請從右上角開始順時針旋轉測試。",
		sampleRing: "使用自動採樣環",
		startTest: "開始測試(空白鍵)",
		autoRetest: "自動重測",
		saveData: "保存數據(Enter鍵)",
		saveOnSwitch: "測試開關功能時保存",
		model: "測試機種",
		saved: "數據已保存",
		nowDV: "現在分壓",
		leftDV: "左複歸分壓",
		rightDV: "右複歸分壓",
		returnAccuracy: "複歸精度",
		upDV: "上複歸分壓",
		downDV: "下複歸分壓",
		checkSaved: "查看已存數據",
		compensation: "校正方案模擬",
		centerDV: "中心分壓",
		DVRange: "大小分壓",
		direction: "方向",
		wobble: "復歸",
		switch: "開關",
		useReturnCenter: "採用複歸中心計算",
		rangeDV: "雙邊行程：",
		rangeMax: "範圍上限",
		returnErr: "單向公差: 50% ± ",
		onesideDV: "單邊行程 ≧ ",
		singleDirectionLifeTest: "單向壽命測試",
		LJoystick: "左搖桿",
		RJoystick: "右搖桿",
		testRange: "範圍",
		noiseMax: "雜訊上限",
		affectAxis: "影響其他軸輸出",
		cleanTrack: "定時清空",
		sec: "秒",
		noise: "雜訊",
		interference: "干擾",
		sw: "開關",
		up: "上",
		down: "下",
		left: "左",
		right: "右",
		clear: "清空",
		detail: "詳細數據",
		xAxis: "X 軸",
		yAxis: "Y 軸"
	}
};

// 切換語言的函數
function switchLanguage(language) {
	// 存儲選擇的語言到 localStorage
    localStorage.setItem('language', language);
	// 獲取所有需要翻譯的元素
	const elements = document.querySelectorAll('[data-key]');
	
	// 遍歷每個元素並更新其文本內容
	elements.forEach(element => {
		const key = element.getAttribute('data-key');
		element.textContent = translations[language][key];
	});
}

// 頁面加載時應用存儲的語言設置
document.addEventListener('DOMContentLoaded', () => {
	const language = localStorage.getItem('language') || 'zh';
	switchLanguage(language);
});